table 'Student Details'
	lineageTag: 4a2bb669-ce6a-4a2c-9526-b43b1caecd1a

	column Student_ID
		dataType: int64
		formatString: 0
		lineageTag: b4568f8b-7f10-4959-bc87-9d1f667b1a2f
		summarizeBy: none
		sourceColumn: Student_ID

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 81efa1db-d097-4f5c-93cb-da3d850fcd1e
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 37d6ecaf-7753-4782-976c-737c7c1c2f30
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Academic_Level
		dataType: string
		lineageTag: e5e0696f-a6be-4c7e-b3db-444dfdab3923
		summarizeBy: none
		sourceColumn: Academic_Level

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6730b8e8-7f57-406f-9f43-5dcea9f160c2
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Sleep_Hours_Per_Night
		dataType: double
		isHidden
		lineageTag: 5cae8982-a8e7-4ce0-89a2-5b6a204818b0
		summarizeBy: sum
		sourceColumn: Sleep_Hours_Per_Night

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Mental_Health_Score
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 20f03ebb-e3b4-4d2e-88f9-db1140ddfb44
		summarizeBy: sum
		sourceColumn: Mental_Health_Score

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Relationship_Status
		dataType: string
		lineageTag: ca6383a2-022b-448a-96d0-575412748385
		summarizeBy: none
		sourceColumn: Relationship_Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Conflicts_Over_Social_Media
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b5768ddd-d98c-46bf-89e4-bd89b2f25060
		summarizeBy: sum
		sourceColumn: Conflicts_Over_Social_Media

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Addicted_Score
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: abbe4d3f-f8ab-4acf-8f58-46a8d0e4de65
		summarizeBy: sum
		sourceColumn: Addicted_Score

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Student Details' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Desktop\power bi\Project\4453437-Dataset\Dataset\Students Social Media Addiction.xlsx"), null, true),
				    #"Student Details_Sheet" = Source{[Item="Student Details",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Student Details_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Student_ID", Int64.Type}, {"Age", Int64.Type}, {"Gender", type text}, {"Academic_Level", type text}, {"Country", type text}, {"Sleep_Hours_Per_Night", type number}, {"Mental_Health_Score", Int64.Type}, {"Relationship_Status", type text}, {"Conflicts_Over_Social_Media", Int64.Type}, {"Addicted_Score", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Filtered Rows", {{"Student_ID", type text}}, "en-IN"),{{"Student_ID", Text.Trim, type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Trimmed Text",{{"Student_ID", Int64.Type}}),
				    #"Trimmed Text1" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type1", {{"Age", type text}}, "en-IN"),{{"Age", Text.Trim, type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Trimmed Text1",{{"Age", Int64.Type}}),
				    #"Trimmed Text2" = Table.TransformColumns(#"Changed Type2",{{"Gender", Text.Trim, type text}, {"Academic_Level", Text.Trim, type text}, {"Country", Text.Trim, type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Trimmed Text2", each true),
				    #"Trimmed Text3" = Table.TransformColumns(Table.TransformColumnTypes(#"Filtered Rows1", {{"Sleep_Hours_Per_Night", type text}}, "en-IN"),{{"Sleep_Hours_Per_Night", Text.Trim, type text}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Trimmed Text3",{{"Sleep_Hours_Per_Night", type number}}),
				    #"Filtered Rows2" = Table.SelectRows(#"Changed Type3", each true),
				    #"Trimmed Text4" = Table.TransformColumns(Table.TransformColumnTypes(#"Filtered Rows2", {{"Mental_Health_Score", type text}}, "en-IN"),{{"Mental_Health_Score", Text.Trim, type text}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Trimmed Text4",{{"Mental_Health_Score", Int64.Type}}),
				    #"Filtered Rows3" = Table.SelectRows(#"Changed Type4", each true),
				    #"Trimmed Text5" = Table.TransformColumns(#"Filtered Rows3",{{"Relationship_Status", Text.Trim, type text}}),
				    #"Filtered Rows4" = Table.SelectRows(#"Trimmed Text5", each true),
				    #"Trimmed Text6" = Table.TransformColumns(Table.TransformColumnTypes(#"Filtered Rows4", {{"Conflicts_Over_Social_Media", type text}}, "en-IN"),{{"Conflicts_Over_Social_Media", Text.Trim, type text}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Trimmed Text6",{{"Conflicts_Over_Social_Media", Int64.Type}}),
				    #"Filtered Rows5" = Table.SelectRows(#"Changed Type5", each true),
				    #"Trimmed Text7" = Table.TransformColumns(Table.TransformColumnTypes(#"Filtered Rows5", {{"Addicted_Score", type text}}, "en-IN"),{{"Addicted_Score", Text.Trim, type text}}),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Trimmed Text7",{{"Addicted_Score", Int64.Type}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type6", {"Student_ID"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

